# Complexity
#   * Number of languages
NUMBER_OF_LANGUAGES_UPPER = 10
NUMBER_OF_LANGUAGES_LOWER = 1
#   * Number of lines per language
AMOUNT_OF_BYTES_PER_LANGUAGE_UPPER = 1000000
AMOUNT_OF_BYTES_PER_LANGUAGE_LOWER = 1000
#   * Number of dependencies
NUMBER_OF_DEPENDENCIES_UPPER = 100
NUMBER_OF_DEPENDENCIES_LOWER = 1
#   * Number of files
NUMBER_OF_FILES_UPPER = 1000
NUMBER_OF_FILES_LOWER = 1
#   * Number of commits
NUMBER_OF_COMMITS_UPPER = 1000
NUMBER_OF_COMMITS_LOWER = 1

# * Useful/Impactful-ness:
#   * Number of stars
NUMBER_OF_STARS_UPPER = 1000
NUMBER_OF_STARS_LOWER = 0
#   * Number of forks
NUMBER_OF_FORKS_UPPER = 1000
NUMBER_OF_FORKS_LOWER = 0
#   * Number of watchers
NUMBER_OF_WATCHERS_UPPER = 1000
NUMBER_OF_WATCHERS_LOWER = 0
#   * Number of pull requests
NUMBER_OF_PULL_REQUESTS_UPPER = 1000
NUMBER_OF_PULL_REQUESTS_LOWER = 0
#   * Number of issues
NUMBER_OF_ISSUES_UPPER = 1000
NUMBER_OF_ISSUES_LOWER = 0
